language: ruby
dist: xenial
rvm:
  - 2.5
addons:
  apt:
    update: true
  packages:
    - curl
    - git
    - make
    - ruby-bundler
    - ruby-dev
    - libxml2-dev
    - libxslt-dev
    - npm
    - openssl
  snaps:
    - jq
    - yq
    - name: aws-cli
      confinement: classic # or devmode
    - name: node
      confinement: classic # or devmode
      channel: 10/stable
env:
  global:
git:
  submodules: false
before_install:
  - gem update --system
  - gem install bundler
  - >-
    openssl aes-256-cbc
    -K $encrypted_74174692c709_key
    -iv $encrypted_74174692c709_iv
    -in github_deploy_key.enc
    -out github_deploy_key
    -d
  - chmod 600 github_deploy_key
  - eval $(ssh-agent -s)
  - ssh-add github_deploy_key
  - make update-init update-modules
before_script:
  - bundle
install:
script:
  - make _site
deploy:
  - provider: script
    script: >-
      aws s3 sync _site s3://$S3_BUCKET_NAME --region=$AWS_REGION --delete --no-progress --exclude "*" --include "*.html" --content-type "text/html; charset=utf-8" &&
      aws s3 sync _site s3://$S3_BUCKET_NAME --region=$AWS_REGION --delete --no-progress --exclude "*" --include "*.json" --content-type "text/json; charset=utf-8" &&
      aws s3 sync _site s3://$S3_BUCKET_NAME --region=$AWS_REGION --delete --no-progress --exclude "*.html,*.json" --include "*"
    skip_cleanup: true
    on:
      branch: master
  - provider: script
    script: >-
      aws s3 sync _site s3://$S3_BUCKET_NAME --region=$AWS_REGION --delete --no-progress --exclude "*" --include "*.html" --content-type "text/html; charset=utf-8" &&
      aws s3 sync _site s3://$S3_BUCKET_NAME --region=$AWS_REGION --delete --no-progress --exclude "*" --include "*.json" --content-type "text/json; charset=utf-8" &&
      aws s3 sync _site s3://$S3_BUCKET_NAME --region=$AWS_REGION --delete --no-progress --exclude "*.html,*.json" --include "*"
    skip_cleanup: true
    on:
      branch: staging
after_deploy:
  - aws configure set preview.cloudfront true
  - test $TRAVIS_BRANCH = "master" && aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRIBUTION_ID --paths "/*"
  - test $TRAVIS_BRANCH = "staging" && aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_STAGING_DISTRIBUTION_ID --paths "/*"

