name: deploy-staging

on:
  push:
    branches: staging

jobs:
  build:
    name: Build site
    runs-on: ubuntu-latest
    steps:
      - name: Setup prerequisites
        run: |
          sudo apt-get update
          sudo apt-get install -y curl make libxml2-dev libxslt-dev openssl
      - name: Setup snaps
        run: |
          sudo snap install yq
          sudo snap install aws-cli --classic
          sudo snap install node --classic --channel=10/stable
      - name: Use Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.6'
          architecture: 'x64'
      - name: Use Node
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - uses: actions/checkout@v2
      - name: Setup git submodules (authenticated)
        env:
          GLOSSARY_DEPLOY_KEY: ${{ secrets.GLOSSARY_DEPLOY_KEY }}
          GIT_SSH_COMMAND: "ssh -o StrictHostKeyChecking=no"
        run: |
          eval "$(ssh-agent -s)"
          ssh-add - <<< "${GLOSSARY_DEPLOY_KEY}"
          make update-init update-modules
      - name: Update gems
        run: |
          gem install bundler -v "~> 2"
          bundle install --jobs 4 --retry 3
      - name: Setup npm
        run: |
          npm install
      - name: Build site
        run: |
          make all


      - name: Deploy to geolexica.org
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          CLOUDFRONT_DISTRIBUTION_ID: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID_STAGING }}
          S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME_STAGING }}
        run: |
          rake geolexica:s3_deploy
